platform :ios, '14.0'

target 'CurrencyConverter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyConverter

  pod 'DropDown'

  target 'CurrencyConverterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurrencyConverterUITests' do
    # Pods for testing
  end

end
