platform :ios, '14.0'
use_frameworks!

target 'CurrencyConverter' do
  
  pod 'DropDown'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'CurrencyConverterTests' do
    inherit! :search_paths
    pod 'RxBlocking'
    pod 'RxTest'
  end

  target 'CurrencyConverterUITests' do
    # Pods for testing
  end

end
